---
- name: Install dependencies for backup execution
  ansible.builtin.apt:
    name: "{{ __nextcloud_backup_dependencies }}"
    state: present
    update_cache: true

- name: Deploy the backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: "{{ __nextcloud_installation_directory }}/backup.sh"
    owner: root
    group: root
    mode: "0700"
  when: nextcloud_backup_directory is defined and nextcloud_backup_directory

- name: Create cron task for the backup
  ansible.builtin.cron:
    name: Nextcloud backup
    job: "{{ __nextcloud_installation_directory }}/backup.sh"
    minute: "{{ nextcloud_backup_cron.minute | default(omit) }}"
    hour: "{{ nextcloud_backup_cron.hour | default(omit) }}"
    day: "{{ nextcloud_backup_cron.day | default(omit) }}"
    month: "{{ nextcloud_backup_cron.month | default(omit) }}"
    weekday: "{{ nextcloud_backup_cron.weekday | default(omit) }}"
    user: root
  when: nextcloud_backup_directory is defined and nextcloud_backup_directory
