---
# tasks file for ansible-role-nextcloud

- name: Install nextcloud
  ansible.builtin.include_tasks: install.yml

- name: Configure nextcloud
  ansible.builtin.include_tasks: configure.yml

- name: Configure backup
  ansible.builtin.include_tasks: backup.yml
